name: CI with Cache

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: prime-cache-f79492f
      id: cache-step
      uses: actions/cache@v4
      with:
        key: cache-f79492f
        path: ~/.npm

    - name: Echo cache result
      run: |
        echo "Cache result: ${{ steps.cache-step.outputs.cache-hit }}"

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
